<a href="https://colab.research.google.com/github/kavyabalaguru/vyakya-assignment/blob/main/Task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded =files.upload()

Saving task_input_list.json to task_input_list.json

In [30]:
import pandas as pd
data=pd.read_json("task_input_list.json")
data

                                        0
0                                ABC BANK
1                       Preferred Rewards
2                          P.O. Box 12345
3            Customer service information
4                   Wilmington, DE 144444
..                                    ...
210    Memo 4100390077958227 815830260521
211  Authorizedby your Depositor 11/27/18
212                           Page 5 of 6
213    This page intentionally left blank
214                           Page 6 of 6

[215 rows x 1 columns]

In [67]:
data.rename(columns={0:'info'}, inplace=True)

In [87]:
df1=data[:35:]
df1

                                                 info
0                                            ABC BANK
1                                   Preferred Rewards
2                                      P.O. Box 12345
3                        Customer service information
4                               Wilmington, DE 144444
5                                                   0
6                                  ph: (555) 555-1234
7             TDD/TTY users only call: (800) 555-1234
8                               other: 1-800-555-1234
9                                            John Doe
10                                bankingservices.com
11                              Your Adv Plus Banking
12                         Preferred Rewards Platinum
13         for November 27, 2018 to December 24, 2018
14                                    Account summary
15             Beginning balance on November 27, 2018
16                                         $83,576.78
17                       Deposits and other additions
18                                          27,450.00
19                    ATM and debit card subtractions
20                                              -0.00
21                                 Other subtractions
22                                         -50,923.23
23                                             Checks
24                                            -949.00
25                                       Service fees
26                                             -40.00
27                Ending balance on December 24, 2018
28                                         $59,114.55
29     See all your benefits and rewards in one place
30  My Rewards lets you see your Preferred Rewards...
31                                            Rewards
32       other rewards and benefits available to you.
33  Check out My Rewards at bankingservices.com/My...
34                                        Page 1 of 6

In [90]:
df2=data[73:133]
df2

                                                  info
73              November 27, 2018 to December 24, 2018
74                        Deposits and other additions
75                                                Date
76                                         Description
77                                              Amount
78                                            12/03/18
79                                      Counter Credit
80                                            8,075.00
81                                            12/10/18
82                                      Counter Credit
83                                            9,970.00
84                                            12/21/18
85                                              PAYPAL
86                 DES:TRANSFER ID:1004561753452 INDN:
87                                                  CO
88                                            1,000.00
89                                            12/24/18
90                                      Counter Credit
91                                            8,405.00
92                  Total deposits and other additions
93                                          $27,450.00
94                  Withdrawals and other subtractions
95                                  Other subtractions
96                                                Date
97                                         Description
98                                              Amount
99                                            11/30/18
100  Automatic Transfer to SAV 2084 Confirmation# 1...
101                                             -25.00
102                                           12/03/18
103  Online Banking payment to CRD 8610 Confirmatio...
104                                            -200.00
105                                           12/04/18
106                          Customer Withdrawal Image
107                                         -12,000.00
108                                           12/07/18
109                                          TRANSFER
110                                          -3,695.00
111                                           12/11/18
112                                             CARFAX
113                DES:BT1210 ID:000000071591462 INDN:
114                                   CO ID:1251465303
115                                            -399.98
116                                           12/13/18
117         TRANSFER  :J Cars Confirmation# 0472167145
118                                          -3,955.00
119                                           12/19/18
120         TRANSFER  :J Cars Confirmation# 0423610629
121                                         -13,990.00
122                                           12/20/18
123                              SOUTHWEST GAS DES:WEB
124                      ID:1410023972050 INDN:JOHNSON
125                                                 CO
126                                             -28.25
127                                           12/21/18
128         TRANSFER  :J Cars Confirmation# 1642822709
129                                         -16,630.00
130                           Total other subtractions
131                                        -$50,923.23
132                                        Page 3 of 6

In [86]:
import re
df=str(data['info'])
lst = re.findall('\S+@\S+', df)
lst

[]

In [89]:
df1=str(df1['info'])
r = re.compile(r'(\d{3}[-\.\s]??\d{3}[-\.\s]??\d{4}|\(\d{3}\)\s*\d{3}[-\.\s]??\d{4}|\d{3}[-\.\s]??\d{4})')
results = r.findall(df1)
results

['(555) 555-1234', '(800) 555-1234', '800-555-1234']